config/routes.rb
Rails.application.routes.draw do
  root 'gifs#index'
  resources :gifs, :only => [:index, :new, :show, :create]
  resources :charges, :only => [:new, :create]

  get 'tags/:tag', to: 'gifs#index', as: "tag"

  post 'gifs/:id/upvote' => 'gifs#upvote', :as => :upvote
  post 'gifs/:id/downvote' => 'gifs#downvote', :as => :downvote

  devise_for :users, controllers: {
    confirmations:  "users/confirmations",
    passwords:      "users/passwords",
    registrations:  "users/registrations",
    sessions:       "users/sessions",
    unlocks:        "users/unlocks"
  }

end

app/models/gif.rb
class Gif < ActiveRecord::Base
  validates :url, uniqueness: true, on: [:create, :edit, :update, :destroy], :allow_blank => true
  validates_format_of :url,
                      :with => /\.gif\z/,
                      :on => [:create, :edit, :update, :destroy],
                      :allow_blank => true,
                      :message => "Gifs only!"
  acts_as_votable
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings
  #Alias for the db column "cached_votes_score"
  alias_attribute :score, :cached_votes_score

  #Did not know that ActiveRecord .where could accept a symbol
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end


end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :set_gif, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy, :upvote, :downvote]

  # GET /gifs
  # GET /gifs.json
  def index
    if params[:tag]
      @gifs = Tag.tagged_with(params[:tag])
      @gif = Gif.new
      respond_to do |format|
        format.html {}
        format.js {}
      end
    else
      @gifs = Gif.order("cached_votes_score DESC")
      @gif = Gif.new
      respond_to do |format|
        format.html {}
        format.js {}
      end
    end
  end

  def upvote
    current_user.likes(@gif)
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def downvote
    current_user.dislikes(@gif)
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  # GET /gifs/1
  # GET /gifs/1.json
  def show
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
  end

  # GET /gifs/1/edit
  def edit
  end

  # POST /gifs
  # POST /gifs.json
  def create
    @gif = Gif.new(gif_params)
    @gif.user_id = current_user.id
    if @gif.save
      @gifs = Gif.order("cached_votes_score DESC").reject{|gif| gif.id == @gif.id}
      @gifs.unshift(@gif)
      respond_to do |format|
        format.js {}
      end
    else
      respond_to do |format|
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /gifs/1
  # PATCH/PUT /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: 'Gif was successfully updated.' }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1
  # DELETE /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: 'Gif was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_gif
      @gif = Gif.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gif_params
      params.require(:gif).permit(:url, :all_tags, :file)
    end
end

app/helpers/gifs_helper.rb
module GifsHelper

  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip), :remote => true, :class => "btn btn-default glyphicon glyphicon-tags", :method => :get}.join(" ")
  end

end

app/views/gifs/_form.html.erb
<%= bootstrap_form_for(@gif, remote: true, authenticity_token: true) do |f| %>
  <% if @gif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gif.errors.count, "error") %> prohibited this gif from being saved:</h2>
      <ul>
      <% @gif.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :url, placeholder: "Make sure your url ends in '.gif'!" %>
  </div>

  <div class="field">
    <%= f.text_field :all_tags, placeholder: "Tags separated with a comma." %>
  </div>

  <div class="actions">
    <%= f.submit :class => "brn btn-primary" %>
  </div>
<% end %>

app/views/gifs/_gif.html.erb
<% gifs.each_slice(4) do |row| %>
  <div class="row">
    <% row.each do |gif| %>
      <div class="col-xs-6 col-sm-3">
        <%= link_to gif_path(:id => gif.id), :remote => true, "data-toggle" => "modal", "data-target" => "#gif-#{gif.id}-modal" do %>
          <div class="gif-<%=gif.id%> gif">
              <img src="<%=gif.url%>" class="img-responsive" alt="No Gif Found!!!"/>
            <div class="vote-<%=gif.id%> vote">
              <%=render :partial => 'gifs/votelinks', :remote => true, :locals => {:gif => gif} %>
            </div>
          </div>
        <% end %>
      </div>
      <%= render :partial => 'gifs/show', :layout => 'layouts/modal', :locals => {:gif => gif, :title => "", :id => "gif-#{gif.id}-modal"} %>
    <% end %>
  </div>
<% end %>

app/views/gifs/_show.html.erb
<div class="row">
  <div class="col-xs-12">
      <img src="<%=gif.url%>" class="img-responsive center-block" alt="No Gif Found!!!"/>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 gif-<%=gif.id%> gif-text">
    <p><strong>Submitted by: </strong><%=gif.user.email%>, <em><%= time_ago_in_words(gif.created_at)%> ago</em></p>
    <% if gif.url %>
      <p><strong>Source: </strong><%=link_to gif.url, gif.url %></p>
    <% end %>
    <p><strong>Tags: </strong><%= raw tag_links(gif.all_tags) || "N/A" %></p>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 vote-<%=gif.id%> vote-modal">
    <p><strong>Vote:</p>
    <%=render :partial => 'gifs/votelinks', :remote => true, :display => "show", :locals => {:gif => gif} %>
  </div>
</div>

app/views/gifs/_votelinks.html.erb
<div class ="col-xs-2 gif-score img-responsive">
  <% if user_signed_in? && !current_user.upvoted?(gif) %>
    <%= link_to upvote_path(:id => gif.id), :remote => true, :method => :post do %>
      <i class="glyphicon glyphicon-chevron-up"></i>
    <% end %>
  <% end %>
  <h4><%= gif.score %></h4>
  <% if user_signed_in? && !current_user.downvoted?(gif) %>
    <%= link_to downvote_path(:id => gif.id), :remote => true, :method => :post do %>
      <i class="glyphicon glyphicon-chevron-down"></i>
    <% end %>
  <% end %>
</div>

app/views/gifs/create.js.erb
$("#gifs-list").html("<%=escape_javascript(render :partial => 'gifs/gif', :locals => {:gifs => @gifs})%>");
$("#newGif").modal('hide');
$('#new_gif')[0].reset();

app/views/gifs/downvote.js.erb
$('.vote-<%=@gif.id%>').html("<%= escape_javascript render(:partial => 'gifs/votelinks', :locals => { :gif => @gif }) %>")

app/views/gifs/edit.html.erb
<h1>Editing Gif</h1>

<%= render 'form' %>

<%= link_to 'Show', @gif %> |
<%= link_to 'Back', gifs_path %>

app/views/gifs/index.html.erb
<div id="tag">

</div>

<% if user_signed_in? %>
  <%= link_to 'New Gif', new_gif_path, :class => "btn btn-primary", :remote => true, "data-toggle" => "modal", "data-target" => "#newGif" %>
<% end %>

<div id="gifs-list" class="container">
  <%= render :partial => 'gif', :locals => {:gifs => @gifs}%>
</div>

app/views/gifs/index.js.erb
// Lines 2-4 came from talking with Caleb about a similar issue he had rendering a view out of a modal
// These lines are needed to hide the backdrop from the bootstrap modal.
$('.modal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();
<% if params[:tag] && !params[:tag].empty? %>
  $('#tag').html('<h4>Gifs tagged with: <em><%= params[:tag] %></em> <%= link_to "Clear", gifs_path, remote: :true %></h4>');
<% else %>
  $('#tag').html('');
<% end %>
$("#gifs-list").html("<%=escape_javascript(render :partial => 'gifs/gif', :locals => {:gifs => @gifs})%>");

app/views/gifs/new.html.erb
<h1>New Gif</h1>

<%= render 'form' %>

<%= link_to 'Back', gifs_path %>

app/views/gifs/new.js.erb
$("#newGif .modal-body").html('<%= escape_javascript( render :partial => "gifs/form" ) %>');
$("#newGif").modal('show');

app/views/gifs/show.html.erb
<% if @gif.url %>
  <p><strong>Url:</strong><%= @gif.url%></p>
<% end %>
<p><strong>Submitted by:</strong><%= @gif.user.email%></p>

app/views/gifs/upvote.js.erb
$('.vote-<%=@gif.id%>').html("<%= escape_javascript render(:partial => 'gifs/votelinks', :locals => { :gif => @gif }) %>")